//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace KKB.Treasury.TreasuryReport.DSD_Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_TR146OBOPFXCF")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_TR146OBOPFXCF : global::System.Data.DataSet {
        
        private TB_TR146OBOPFXCFDataTable tableTB_TR146OBOPFXCF;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_TR146OBOPFXCF() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_TR146OBOPFXCF(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TB_TR146OBOPFXCF"] != null)) {
                    base.Tables.Add(new TB_TR146OBOPFXCFDataTable(ds.Tables["TB_TR146OBOPFXCF"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TB_TR146OBOPFXCFDataTable TB_TR146OBOPFXCF {
            get {
                return this.tableTB_TR146OBOPFXCF;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DS_TR146OBOPFXCF cln = ((DS_TR146OBOPFXCF)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TB_TR146OBOPFXCF"] != null)) {
                    base.Tables.Add(new TB_TR146OBOPFXCFDataTable(ds.Tables["TB_TR146OBOPFXCF"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTB_TR146OBOPFXCF = ((TB_TR146OBOPFXCFDataTable)(base.Tables["TB_TR146OBOPFXCF"]));
            if ((initTable == true)) {
                if ((this.tableTB_TR146OBOPFXCF != null)) {
                    this.tableTB_TR146OBOPFXCF.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_TR146OBOPFXCF";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_TR146OBOPFXCF.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTB_TR146OBOPFXCF = new TB_TR146OBOPFXCFDataTable();
            base.Tables.Add(this.tableTB_TR146OBOPFXCF);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTB_TR146OBOPFXCF() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_TR146OBOPFXCF ds = new DS_TR146OBOPFXCF();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TB_TR146OBOPFXCFRowChangeEventHandler(object sender, TB_TR146OBOPFXCFRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TB_TR146OBOPFXCFDataTable : global::System.Data.TypedTableBase<TB_TR146OBOPFXCFRow> {
            
            private global::System.Data.DataColumn columnFUND;
            
            private global::System.Data.DataColumn columnSHORTNAME;
            
            private global::System.Data.DataColumn columnFUNDNAME;
            
            private global::System.Data.DataColumn columnDEALNO;
            
            private global::System.Data.DataColumn columnDEALDATE;
            
            private global::System.Data.DataColumn columnVDATE;
            
            private global::System.Data.DataColumn columnBUYCCY;
            
            private global::System.Data.DataColumn columnBUYAMT;
            
            private global::System.Data.DataColumn columnSELLCCY;
            
            private global::System.Data.DataColumn columnSELLAMT;
            
            private global::System.Data.DataColumn columnCCYRATE_8;
            
            private global::System.Data.DataColumn columnTENOR;
            
            private global::System.Data.DataColumn columnSWAPPOINT;
            
            private global::System.Data.DataColumn columnPURPOSECODE;
            
            private global::System.Data.DataColumn columnPURPOSEDESC;
            
            private global::System.Data.DataColumn columnSHOWTENOR;
            
            private global::System.Data.DataColumn columnSHOWSWAPPOINT;
            
            private global::System.Data.DataColumn columnCTYPE;
            
            private global::System.Data.DataColumn columnREMARK;
            
            private global::System.Data.DataColumn columnCONFIRMTYPE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFDataTable() {
                this.TableName = "TB_TR146OBOPFXCF";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR146OBOPFXCFDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TB_TR146OBOPFXCFDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FUNDColumn {
                get {
                    return this.columnFUND;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SHORTNAMEColumn {
                get {
                    return this.columnSHORTNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FUNDNAMEColumn {
                get {
                    return this.columnFUNDNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DEALNOColumn {
                get {
                    return this.columnDEALNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DEALDATEColumn {
                get {
                    return this.columnDEALDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn VDATEColumn {
                get {
                    return this.columnVDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BUYCCYColumn {
                get {
                    return this.columnBUYCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BUYAMTColumn {
                get {
                    return this.columnBUYAMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SELLCCYColumn {
                get {
                    return this.columnSELLCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SELLAMTColumn {
                get {
                    return this.columnSELLAMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYRATE_8Column {
                get {
                    return this.columnCCYRATE_8;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TENORColumn {
                get {
                    return this.columnTENOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWAPPOINTColumn {
                get {
                    return this.columnSWAPPOINT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PURPOSECODEColumn {
                get {
                    return this.columnPURPOSECODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PURPOSEDESCColumn {
                get {
                    return this.columnPURPOSEDESC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SHOWTENORColumn {
                get {
                    return this.columnSHOWTENOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SHOWSWAPPOINTColumn {
                get {
                    return this.columnSHOWSWAPPOINT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CTYPEColumn {
                get {
                    return this.columnCTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn REMARKColumn {
                get {
                    return this.columnREMARK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CONFIRMTYPEColumn {
                get {
                    return this.columnCONFIRMTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFRow this[int index] {
                get {
                    return ((TB_TR146OBOPFXCFRow)(this.Rows[index]));
                }
            }
            
            public event TB_TR146OBOPFXCFRowChangeEventHandler TB_TR146OBOPFXCFRowChanging;
            
            public event TB_TR146OBOPFXCFRowChangeEventHandler TB_TR146OBOPFXCFRowChanged;
            
            public event TB_TR146OBOPFXCFRowChangeEventHandler TB_TR146OBOPFXCFRowDeleting;
            
            public event TB_TR146OBOPFXCFRowChangeEventHandler TB_TR146OBOPFXCFRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTB_TR146OBOPFXCFRow(TB_TR146OBOPFXCFRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFRow AddTB_TR146OBOPFXCFRow(
                        string FUND, 
                        string SHORTNAME, 
                        string FUNDNAME, 
                        string DEALNO, 
                        string DEALDATE, 
                        string VDATE, 
                        string BUYCCY, 
                        decimal BUYAMT, 
                        string SELLCCY, 
                        decimal SELLAMT, 
                        decimal CCYRATE_8, 
                        decimal TENOR, 
                        decimal SWAPPOINT, 
                        string PURPOSECODE, 
                        string PURPOSEDESC, 
                        string SHOWTENOR, 
                        string SHOWSWAPPOINT, 
                        string CTYPE, 
                        string REMARK, 
                        string CONFIRMTYPE) {
                TB_TR146OBOPFXCFRow rowTB_TR146OBOPFXCFRow = ((TB_TR146OBOPFXCFRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        FUND,
                        SHORTNAME,
                        FUNDNAME,
                        DEALNO,
                        DEALDATE,
                        VDATE,
                        BUYCCY,
                        BUYAMT,
                        SELLCCY,
                        SELLAMT,
                        CCYRATE_8,
                        TENOR,
                        SWAPPOINT,
                        PURPOSECODE,
                        PURPOSEDESC,
                        SHOWTENOR,
                        SHOWSWAPPOINT,
                        CTYPE,
                        REMARK,
                        CONFIRMTYPE};
                rowTB_TR146OBOPFXCFRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTB_TR146OBOPFXCFRow);
                return rowTB_TR146OBOPFXCFRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TB_TR146OBOPFXCFDataTable cln = ((TB_TR146OBOPFXCFDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TB_TR146OBOPFXCFDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnFUND = base.Columns["FUND"];
                this.columnSHORTNAME = base.Columns["SHORTNAME"];
                this.columnFUNDNAME = base.Columns["FUNDNAME"];
                this.columnDEALNO = base.Columns["DEALNO"];
                this.columnDEALDATE = base.Columns["DEALDATE"];
                this.columnVDATE = base.Columns["VDATE"];
                this.columnBUYCCY = base.Columns["BUYCCY"];
                this.columnBUYAMT = base.Columns["BUYAMT"];
                this.columnSELLCCY = base.Columns["SELLCCY"];
                this.columnSELLAMT = base.Columns["SELLAMT"];
                this.columnCCYRATE_8 = base.Columns["CCYRATE_8"];
                this.columnTENOR = base.Columns["TENOR"];
                this.columnSWAPPOINT = base.Columns["SWAPPOINT"];
                this.columnPURPOSECODE = base.Columns["PURPOSECODE"];
                this.columnPURPOSEDESC = base.Columns["PURPOSEDESC"];
                this.columnSHOWTENOR = base.Columns["SHOWTENOR"];
                this.columnSHOWSWAPPOINT = base.Columns["SHOWSWAPPOINT"];
                this.columnCTYPE = base.Columns["CTYPE"];
                this.columnREMARK = base.Columns["REMARK"];
                this.columnCONFIRMTYPE = base.Columns["CONFIRMTYPE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnFUND = new global::System.Data.DataColumn("FUND", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFUND);
                this.columnSHORTNAME = new global::System.Data.DataColumn("SHORTNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSHORTNAME);
                this.columnFUNDNAME = new global::System.Data.DataColumn("FUNDNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFUNDNAME);
                this.columnDEALNO = new global::System.Data.DataColumn("DEALNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDEALNO);
                this.columnDEALDATE = new global::System.Data.DataColumn("DEALDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDEALDATE);
                this.columnVDATE = new global::System.Data.DataColumn("VDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVDATE);
                this.columnBUYCCY = new global::System.Data.DataColumn("BUYCCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYCCY);
                this.columnBUYAMT = new global::System.Data.DataColumn("BUYAMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYAMT);
                this.columnSELLCCY = new global::System.Data.DataColumn("SELLCCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSELLCCY);
                this.columnSELLAMT = new global::System.Data.DataColumn("SELLAMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSELLAMT);
                this.columnCCYRATE_8 = new global::System.Data.DataColumn("CCYRATE_8", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCYRATE_8);
                this.columnTENOR = new global::System.Data.DataColumn("TENOR", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTENOR);
                this.columnSWAPPOINT = new global::System.Data.DataColumn("SWAPPOINT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWAPPOINT);
                this.columnPURPOSECODE = new global::System.Data.DataColumn("PURPOSECODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPURPOSECODE);
                this.columnPURPOSEDESC = new global::System.Data.DataColumn("PURPOSEDESC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPURPOSEDESC);
                this.columnSHOWTENOR = new global::System.Data.DataColumn("SHOWTENOR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSHOWTENOR);
                this.columnSHOWSWAPPOINT = new global::System.Data.DataColumn("SHOWSWAPPOINT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSHOWSWAPPOINT);
                this.columnCTYPE = new global::System.Data.DataColumn("CTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCTYPE);
                this.columnREMARK = new global::System.Data.DataColumn("REMARK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARK);
                this.columnCONFIRMTYPE = new global::System.Data.DataColumn("CONFIRMTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCONFIRMTYPE);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFRow NewTB_TR146OBOPFXCFRow() {
                return ((TB_TR146OBOPFXCFRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TB_TR146OBOPFXCFRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TB_TR146OBOPFXCFRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TB_TR146OBOPFXCFRowChanged != null)) {
                    this.TB_TR146OBOPFXCFRowChanged(this, new TB_TR146OBOPFXCFRowChangeEvent(((TB_TR146OBOPFXCFRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TB_TR146OBOPFXCFRowChanging != null)) {
                    this.TB_TR146OBOPFXCFRowChanging(this, new TB_TR146OBOPFXCFRowChangeEvent(((TB_TR146OBOPFXCFRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TB_TR146OBOPFXCFRowDeleted != null)) {
                    this.TB_TR146OBOPFXCFRowDeleted(this, new TB_TR146OBOPFXCFRowChangeEvent(((TB_TR146OBOPFXCFRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TB_TR146OBOPFXCFRowDeleting != null)) {
                    this.TB_TR146OBOPFXCFRowDeleting(this, new TB_TR146OBOPFXCFRowChangeEvent(((TB_TR146OBOPFXCFRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTB_TR146OBOPFXCFRow(TB_TR146OBOPFXCFRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_TR146OBOPFXCF ds = new DS_TR146OBOPFXCF();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TB_TR146OBOPFXCFDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TB_TR146OBOPFXCFRow : global::System.Data.DataRow {
            
            private TB_TR146OBOPFXCFDataTable tableTB_TR146OBOPFXCF;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR146OBOPFXCFRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTB_TR146OBOPFXCF = ((TB_TR146OBOPFXCFDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FUND {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.FUNDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FUND\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.FUNDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SHORTNAME {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.SHORTNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SHORTNAME\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SHORTNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FUNDNAME {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.FUNDNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FUNDNAME\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.FUNDNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DEALNO {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.DEALNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DEALNO\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.DEALNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DEALDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.DEALDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DEALDATE\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.DEALDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string VDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.VDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'VDATE\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.VDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BUYCCY {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.BUYCCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BUYCCY\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.BUYCCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal BUYAMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR146OBOPFXCF.BUYAMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BUYAMT\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.BUYAMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SELLCCY {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.SELLCCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SELLCCY\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SELLCCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SELLAMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR146OBOPFXCF.SELLAMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SELLAMT\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SELLAMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal CCYRATE_8 {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR146OBOPFXCF.CCYRATE_8Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCYRATE_8\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.CCYRATE_8Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TENOR {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR146OBOPFXCF.TENORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TENOR\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.TENORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SWAPPOINT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR146OBOPFXCF.SWAPPOINTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWAPPOINT\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SWAPPOINTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PURPOSECODE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.PURPOSECODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PURPOSECODE\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.PURPOSECODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PURPOSEDESC {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.PURPOSEDESCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PURPOSEDESC\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.PURPOSEDESCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SHOWTENOR {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.SHOWTENORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SHOWTENOR\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SHOWTENORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SHOWSWAPPOINT {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.SHOWSWAPPOINTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SHOWSWAPPOINT\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.SHOWSWAPPOINTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CTYPE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.CTYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CTYPE\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.CTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string REMARK {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.REMARKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REMARK\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.REMARKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CONFIRMTYPE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR146OBOPFXCF.CONFIRMTYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CONFIRMTYPE\' in table \'TB_TR146OBOPFXCF\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR146OBOPFXCF.CONFIRMTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFUNDNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.FUNDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFUNDNull() {
                this[this.tableTB_TR146OBOPFXCF.FUNDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSHORTNAMENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SHORTNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSHORTNAMENull() {
                this[this.tableTB_TR146OBOPFXCF.SHORTNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFUNDNAMENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.FUNDNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFUNDNAMENull() {
                this[this.tableTB_TR146OBOPFXCF.FUNDNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDEALNONull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.DEALNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDEALNONull() {
                this[this.tableTB_TR146OBOPFXCF.DEALNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDEALDATENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.DEALDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDEALDATENull() {
                this[this.tableTB_TR146OBOPFXCF.DEALDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsVDATENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.VDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetVDATENull() {
                this[this.tableTB_TR146OBOPFXCF.VDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBUYCCYNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.BUYCCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBUYCCYNull() {
                this[this.tableTB_TR146OBOPFXCF.BUYCCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBUYAMTNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.BUYAMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBUYAMTNull() {
                this[this.tableTB_TR146OBOPFXCF.BUYAMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSELLCCYNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SELLCCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSELLCCYNull() {
                this[this.tableTB_TR146OBOPFXCF.SELLCCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSELLAMTNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SELLAMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSELLAMTNull() {
                this[this.tableTB_TR146OBOPFXCF.SELLAMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYRATE_8Null() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.CCYRATE_8Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYRATE_8Null() {
                this[this.tableTB_TR146OBOPFXCF.CCYRATE_8Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTENORNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.TENORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTENORNull() {
                this[this.tableTB_TR146OBOPFXCF.TENORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWAPPOINTNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SWAPPOINTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWAPPOINTNull() {
                this[this.tableTB_TR146OBOPFXCF.SWAPPOINTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPURPOSECODENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.PURPOSECODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPURPOSECODENull() {
                this[this.tableTB_TR146OBOPFXCF.PURPOSECODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPURPOSEDESCNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.PURPOSEDESCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPURPOSEDESCNull() {
                this[this.tableTB_TR146OBOPFXCF.PURPOSEDESCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSHOWTENORNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SHOWTENORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSHOWTENORNull() {
                this[this.tableTB_TR146OBOPFXCF.SHOWTENORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSHOWSWAPPOINTNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.SHOWSWAPPOINTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSHOWSWAPPOINTNull() {
                this[this.tableTB_TR146OBOPFXCF.SHOWSWAPPOINTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCTYPENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.CTYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCTYPENull() {
                this[this.tableTB_TR146OBOPFXCF.CTYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsREMARKNull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.REMARKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetREMARKNull() {
                this[this.tableTB_TR146OBOPFXCF.REMARKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCONFIRMTYPENull() {
                return this.IsNull(this.tableTB_TR146OBOPFXCF.CONFIRMTYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCONFIRMTYPENull() {
                this[this.tableTB_TR146OBOPFXCF.CONFIRMTYPEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TB_TR146OBOPFXCFRowChangeEvent : global::System.EventArgs {
            
            private TB_TR146OBOPFXCFRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFRowChangeEvent(TB_TR146OBOPFXCFRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR146OBOPFXCFRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591