//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace KKB.Treasury.TreasuryReport.DSD_Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_TR142SWIFTREC")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_TR142SWIFTREC : global::System.Data.DataSet {
        
        private TB_TR142SWIFTRECDataTable tableTB_TR142SWIFTREC;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_TR142SWIFTREC() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_TR142SWIFTREC(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TB_TR142SWIFTREC"] != null)) {
                    base.Tables.Add(new TB_TR142SWIFTRECDataTable(ds.Tables["TB_TR142SWIFTREC"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TB_TR142SWIFTRECDataTable TB_TR142SWIFTREC {
            get {
                return this.tableTB_TR142SWIFTREC;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DS_TR142SWIFTREC cln = ((DS_TR142SWIFTREC)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TB_TR142SWIFTREC"] != null)) {
                    base.Tables.Add(new TB_TR142SWIFTRECDataTable(ds.Tables["TB_TR142SWIFTREC"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTB_TR142SWIFTREC = ((TB_TR142SWIFTRECDataTable)(base.Tables["TB_TR142SWIFTREC"]));
            if ((initTable == true)) {
                if ((this.tableTB_TR142SWIFTREC != null)) {
                    this.tableTB_TR142SWIFTREC.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_TR142SWIFTREC";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_TR142SWIFTREC.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTB_TR142SWIFTREC = new TB_TR142SWIFTRECDataTable();
            base.Tables.Add(this.tableTB_TR142SWIFTREC);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTB_TR142SWIFTREC() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_TR142SWIFTREC ds = new DS_TR142SWIFTREC();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TB_TR142SWIFTRECRowChangeEventHandler(object sender, TB_TR142SWIFTRECRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TB_TR142SWIFTRECDataTable : global::System.Data.TypedTableBase<TB_TR142SWIFTRECRow> {
            
            private global::System.Data.DataColumn columnDEALNO;
            
            private global::System.Data.DataColumn columnVDATE;
            
            private global::System.Data.DataColumn columnCCY;
            
            private global::System.Data.DataColumn columnAMT;
            
            private global::System.Data.DataColumn columnSWIFT_REF;
            
            private global::System.Data.DataColumn columnSWIFT_AMT;
            
            private global::System.Data.DataColumn columnSWIFT_STATUS;
            
            private global::System.Data.DataColumn columnSWIFT_NETW_STATUS;
            
            private global::System.Data.DataColumn columnFLAG;
            
            private global::System.Data.DataColumn columnNETTING;
            
            private global::System.Data.DataColumn columnSWIFT_TYPE;
            
            private global::System.Data.DataColumn columnCMNE;
            
            private global::System.Data.DataColumn columnCTYPE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECDataTable() {
                this.TableName = "TB_TR142SWIFTREC";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR142SWIFTRECDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TB_TR142SWIFTRECDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DEALNOColumn {
                get {
                    return this.columnDEALNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn VDATEColumn {
                get {
                    return this.columnVDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYColumn {
                get {
                    return this.columnCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AMTColumn {
                get {
                    return this.columnAMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWIFT_REFColumn {
                get {
                    return this.columnSWIFT_REF;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWIFT_AMTColumn {
                get {
                    return this.columnSWIFT_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWIFT_STATUSColumn {
                get {
                    return this.columnSWIFT_STATUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWIFT_NETW_STATUSColumn {
                get {
                    return this.columnSWIFT_NETW_STATUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FLAGColumn {
                get {
                    return this.columnFLAG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NETTINGColumn {
                get {
                    return this.columnNETTING;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SWIFT_TYPEColumn {
                get {
                    return this.columnSWIFT_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CMNEColumn {
                get {
                    return this.columnCMNE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CTYPEColumn {
                get {
                    return this.columnCTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECRow this[int index] {
                get {
                    return ((TB_TR142SWIFTRECRow)(this.Rows[index]));
                }
            }
            
            public event TB_TR142SWIFTRECRowChangeEventHandler TB_TR142SWIFTRECRowChanging;
            
            public event TB_TR142SWIFTRECRowChangeEventHandler TB_TR142SWIFTRECRowChanged;
            
            public event TB_TR142SWIFTRECRowChangeEventHandler TB_TR142SWIFTRECRowDeleting;
            
            public event TB_TR142SWIFTRECRowChangeEventHandler TB_TR142SWIFTRECRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTB_TR142SWIFTRECRow(TB_TR142SWIFTRECRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECRow AddTB_TR142SWIFTRECRow(string DEALNO, string VDATE, string CCY, decimal AMT, string SWIFT_REF, decimal SWIFT_AMT, string SWIFT_STATUS, string SWIFT_NETW_STATUS, string FLAG, string NETTING, string SWIFT_TYPE, string CMNE, string CTYPE) {
                TB_TR142SWIFTRECRow rowTB_TR142SWIFTRECRow = ((TB_TR142SWIFTRECRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DEALNO,
                        VDATE,
                        CCY,
                        AMT,
                        SWIFT_REF,
                        SWIFT_AMT,
                        SWIFT_STATUS,
                        SWIFT_NETW_STATUS,
                        FLAG,
                        NETTING,
                        SWIFT_TYPE,
                        CMNE,
                        CTYPE};
                rowTB_TR142SWIFTRECRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTB_TR142SWIFTRECRow);
                return rowTB_TR142SWIFTRECRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TB_TR142SWIFTRECDataTable cln = ((TB_TR142SWIFTRECDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TB_TR142SWIFTRECDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDEALNO = base.Columns["DEALNO"];
                this.columnVDATE = base.Columns["VDATE"];
                this.columnCCY = base.Columns["CCY"];
                this.columnAMT = base.Columns["AMT"];
                this.columnSWIFT_REF = base.Columns["SWIFT_REF"];
                this.columnSWIFT_AMT = base.Columns["SWIFT_AMT"];
                this.columnSWIFT_STATUS = base.Columns["SWIFT_STATUS"];
                this.columnSWIFT_NETW_STATUS = base.Columns["SWIFT_NETW_STATUS"];
                this.columnFLAG = base.Columns["FLAG"];
                this.columnNETTING = base.Columns["NETTING"];
                this.columnSWIFT_TYPE = base.Columns["SWIFT_TYPE"];
                this.columnCMNE = base.Columns["CMNE"];
                this.columnCTYPE = base.Columns["CTYPE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDEALNO = new global::System.Data.DataColumn("DEALNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDEALNO);
                this.columnVDATE = new global::System.Data.DataColumn("VDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVDATE);
                this.columnCCY = new global::System.Data.DataColumn("CCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCY);
                this.columnAMT = new global::System.Data.DataColumn("AMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAMT);
                this.columnSWIFT_REF = new global::System.Data.DataColumn("SWIFT_REF", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWIFT_REF);
                this.columnSWIFT_AMT = new global::System.Data.DataColumn("SWIFT_AMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWIFT_AMT);
                this.columnSWIFT_STATUS = new global::System.Data.DataColumn("SWIFT_STATUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWIFT_STATUS);
                this.columnSWIFT_NETW_STATUS = new global::System.Data.DataColumn("SWIFT_NETW_STATUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWIFT_NETW_STATUS);
                this.columnFLAG = new global::System.Data.DataColumn("FLAG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFLAG);
                this.columnNETTING = new global::System.Data.DataColumn("NETTING", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNETTING);
                this.columnSWIFT_TYPE = new global::System.Data.DataColumn("SWIFT_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSWIFT_TYPE);
                this.columnCMNE = new global::System.Data.DataColumn("CMNE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCMNE);
                this.columnCTYPE = new global::System.Data.DataColumn("CTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCTYPE);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECRow NewTB_TR142SWIFTRECRow() {
                return ((TB_TR142SWIFTRECRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TB_TR142SWIFTRECRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TB_TR142SWIFTRECRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TB_TR142SWIFTRECRowChanged != null)) {
                    this.TB_TR142SWIFTRECRowChanged(this, new TB_TR142SWIFTRECRowChangeEvent(((TB_TR142SWIFTRECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TB_TR142SWIFTRECRowChanging != null)) {
                    this.TB_TR142SWIFTRECRowChanging(this, new TB_TR142SWIFTRECRowChangeEvent(((TB_TR142SWIFTRECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TB_TR142SWIFTRECRowDeleted != null)) {
                    this.TB_TR142SWIFTRECRowDeleted(this, new TB_TR142SWIFTRECRowChangeEvent(((TB_TR142SWIFTRECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TB_TR142SWIFTRECRowDeleting != null)) {
                    this.TB_TR142SWIFTRECRowDeleting(this, new TB_TR142SWIFTRECRowChangeEvent(((TB_TR142SWIFTRECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTB_TR142SWIFTRECRow(TB_TR142SWIFTRECRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_TR142SWIFTREC ds = new DS_TR142SWIFTREC();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TB_TR142SWIFTRECDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TB_TR142SWIFTRECRow : global::System.Data.DataRow {
            
            private TB_TR142SWIFTRECDataTable tableTB_TR142SWIFTREC;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR142SWIFTRECRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTB_TR142SWIFTREC = ((TB_TR142SWIFTRECDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DEALNO {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.DEALNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DEALNO\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.DEALNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string VDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.VDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'VDATE\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.VDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CCY {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.CCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCY\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.CCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal AMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR142SWIFTREC.AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AMT\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SWIFT_REF {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.SWIFT_REFColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWIFT_REF\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.SWIFT_REFColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SWIFT_AMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR142SWIFTREC.SWIFT_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWIFT_AMT\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.SWIFT_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SWIFT_STATUS {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.SWIFT_STATUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWIFT_STATUS\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.SWIFT_STATUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SWIFT_NETW_STATUS {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.SWIFT_NETW_STATUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWIFT_NETW_STATUS\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.SWIFT_NETW_STATUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FLAG {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.FLAGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FLAG\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.FLAGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NETTING {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.NETTINGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NETTING\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.NETTINGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SWIFT_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.SWIFT_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SWIFT_TYPE\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.SWIFT_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CMNE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.CMNEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CMNE\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.CMNEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CTYPE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR142SWIFTREC.CTYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CTYPE\' in table \'TB_TR142SWIFTREC\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR142SWIFTREC.CTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDEALNONull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.DEALNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDEALNONull() {
                this[this.tableTB_TR142SWIFTREC.DEALNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsVDATENull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.VDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetVDATENull() {
                this[this.tableTB_TR142SWIFTREC.VDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.CCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYNull() {
                this[this.tableTB_TR142SWIFTREC.CCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAMTNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAMTNull() {
                this[this.tableTB_TR142SWIFTREC.AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWIFT_REFNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.SWIFT_REFColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWIFT_REFNull() {
                this[this.tableTB_TR142SWIFTREC.SWIFT_REFColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWIFT_AMTNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.SWIFT_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWIFT_AMTNull() {
                this[this.tableTB_TR142SWIFTREC.SWIFT_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWIFT_STATUSNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.SWIFT_STATUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWIFT_STATUSNull() {
                this[this.tableTB_TR142SWIFTREC.SWIFT_STATUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWIFT_NETW_STATUSNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.SWIFT_NETW_STATUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWIFT_NETW_STATUSNull() {
                this[this.tableTB_TR142SWIFTREC.SWIFT_NETW_STATUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFLAGNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.FLAGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFLAGNull() {
                this[this.tableTB_TR142SWIFTREC.FLAGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNETTINGNull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.NETTINGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNETTINGNull() {
                this[this.tableTB_TR142SWIFTREC.NETTINGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSWIFT_TYPENull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.SWIFT_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSWIFT_TYPENull() {
                this[this.tableTB_TR142SWIFTREC.SWIFT_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCMNENull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.CMNEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCMNENull() {
                this[this.tableTB_TR142SWIFTREC.CMNEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCTYPENull() {
                return this.IsNull(this.tableTB_TR142SWIFTREC.CTYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCTYPENull() {
                this[this.tableTB_TR142SWIFTREC.CTYPEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TB_TR142SWIFTRECRowChangeEvent : global::System.EventArgs {
            
            private TB_TR142SWIFTRECRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECRowChangeEvent(TB_TR142SWIFTRECRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR142SWIFTRECRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591