//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace KKB.Treasury.TreasuryReport.DSD_Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_TR101OBOCOLS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_TR101OBOCOLS : global::System.Data.DataSet {
        
        private TB_TR101OBOCOLSDataTable tableTB_TR101OBOCOLS;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_TR101OBOCOLS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_TR101OBOCOLS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TB_TR101OBOCOLS"] != null)) {
                    base.Tables.Add(new TB_TR101OBOCOLSDataTable(ds.Tables["TB_TR101OBOCOLS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TB_TR101OBOCOLSDataTable TB_TR101OBOCOLS {
            get {
                return this.tableTB_TR101OBOCOLS;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DS_TR101OBOCOLS cln = ((DS_TR101OBOCOLS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TB_TR101OBOCOLS"] != null)) {
                    base.Tables.Add(new TB_TR101OBOCOLSDataTable(ds.Tables["TB_TR101OBOCOLS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTB_TR101OBOCOLS = ((TB_TR101OBOCOLSDataTable)(base.Tables["TB_TR101OBOCOLS"]));
            if ((initTable == true)) {
                if ((this.tableTB_TR101OBOCOLS != null)) {
                    this.tableTB_TR101OBOCOLS.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_TR101OBOCOLS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_TR101OBOCOLS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTB_TR101OBOCOLS = new TB_TR101OBOCOLSDataTable();
            base.Tables.Add(this.tableTB_TR101OBOCOLS);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTB_TR101OBOCOLS() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_TR101OBOCOLS ds = new DS_TR101OBOCOLS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TB_TR101OBOCOLSRowChangeEventHandler(object sender, TB_TR101OBOCOLSRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TB_TR101OBOCOLSDataTable : global::System.Data.TypedTableBase<TB_TR101OBOCOLSRow> {
            
            private global::System.Data.DataColumn columnCUST;
            
            private global::System.Data.DataColumn columnINDAMOUNT;
            
            private global::System.Data.DataColumn columnINITMARGIN;
            
            private global::System.Data.DataColumn columnCTPY_THRESHOLD;
            
            private global::System.Data.DataColumn columnKK_THRESHOLD;
            
            private global::System.Data.DataColumn columnMIN_TRANSFER;
            
            private global::System.Data.DataColumn columnROUNDING_AMT;
            
            private global::System.Data.DataColumn columnCCY;
            
            private global::System.Data.DataColumn columnSETTLED_AMT;
            
            private global::System.Data.DataColumn columnPENDING_AMT;
            
            private global::System.Data.DataColumn columnEXPOSURE;
            
            private global::System.Data.DataColumn columnLOCAL_CCY_EXP;
            
            private global::System.Data.DataColumn columnREPORT_DATE;
            
            private global::System.Data.DataColumn columnEXP_RETURN;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSDataTable() {
                this.TableName = "TB_TR101OBOCOLS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR101OBOCOLSDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TB_TR101OBOCOLSDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CUSTColumn {
                get {
                    return this.columnCUST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INDAMOUNTColumn {
                get {
                    return this.columnINDAMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INITMARGINColumn {
                get {
                    return this.columnINITMARGIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CTPY_THRESHOLDColumn {
                get {
                    return this.columnCTPY_THRESHOLD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KK_THRESHOLDColumn {
                get {
                    return this.columnKK_THRESHOLD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MIN_TRANSFERColumn {
                get {
                    return this.columnMIN_TRANSFER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ROUNDING_AMTColumn {
                get {
                    return this.columnROUNDING_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYColumn {
                get {
                    return this.columnCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SETTLED_AMTColumn {
                get {
                    return this.columnSETTLED_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENDING_AMTColumn {
                get {
                    return this.columnPENDING_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EXPOSUREColumn {
                get {
                    return this.columnEXPOSURE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LOCAL_CCY_EXPColumn {
                get {
                    return this.columnLOCAL_CCY_EXP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn REPORT_DATEColumn {
                get {
                    return this.columnREPORT_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EXP_RETURNColumn {
                get {
                    return this.columnEXP_RETURN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSRow this[int index] {
                get {
                    return ((TB_TR101OBOCOLSRow)(this.Rows[index]));
                }
            }
            
            public event TB_TR101OBOCOLSRowChangeEventHandler TB_TR101OBOCOLSRowChanging;
            
            public event TB_TR101OBOCOLSRowChangeEventHandler TB_TR101OBOCOLSRowChanged;
            
            public event TB_TR101OBOCOLSRowChangeEventHandler TB_TR101OBOCOLSRowDeleting;
            
            public event TB_TR101OBOCOLSRowChangeEventHandler TB_TR101OBOCOLSRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTB_TR101OBOCOLSRow(TB_TR101OBOCOLSRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSRow AddTB_TR101OBOCOLSRow(string CUST, decimal INDAMOUNT, decimal INITMARGIN, decimal CTPY_THRESHOLD, decimal KK_THRESHOLD, decimal MIN_TRANSFER, decimal ROUNDING_AMT, string CCY, decimal SETTLED_AMT, decimal PENDING_AMT, decimal EXPOSURE, string LOCAL_CCY_EXP, string REPORT_DATE, string EXP_RETURN) {
                TB_TR101OBOCOLSRow rowTB_TR101OBOCOLSRow = ((TB_TR101OBOCOLSRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CUST,
                        INDAMOUNT,
                        INITMARGIN,
                        CTPY_THRESHOLD,
                        KK_THRESHOLD,
                        MIN_TRANSFER,
                        ROUNDING_AMT,
                        CCY,
                        SETTLED_AMT,
                        PENDING_AMT,
                        EXPOSURE,
                        LOCAL_CCY_EXP,
                        REPORT_DATE,
                        EXP_RETURN};
                rowTB_TR101OBOCOLSRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTB_TR101OBOCOLSRow);
                return rowTB_TR101OBOCOLSRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TB_TR101OBOCOLSDataTable cln = ((TB_TR101OBOCOLSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TB_TR101OBOCOLSDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCUST = base.Columns["CUST"];
                this.columnINDAMOUNT = base.Columns["INDAMOUNT"];
                this.columnINITMARGIN = base.Columns["INITMARGIN"];
                this.columnCTPY_THRESHOLD = base.Columns["CTPY_THRESHOLD"];
                this.columnKK_THRESHOLD = base.Columns["KK_THRESHOLD"];
                this.columnMIN_TRANSFER = base.Columns["MIN_TRANSFER"];
                this.columnROUNDING_AMT = base.Columns["ROUNDING_AMT"];
                this.columnCCY = base.Columns["CCY"];
                this.columnSETTLED_AMT = base.Columns["SETTLED_AMT"];
                this.columnPENDING_AMT = base.Columns["PENDING_AMT"];
                this.columnEXPOSURE = base.Columns["EXPOSURE"];
                this.columnLOCAL_CCY_EXP = base.Columns["LOCAL_CCY_EXP"];
                this.columnREPORT_DATE = base.Columns["REPORT_DATE"];
                this.columnEXP_RETURN = base.Columns["EXP_RETURN"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCUST = new global::System.Data.DataColumn("CUST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUST);
                this.columnINDAMOUNT = new global::System.Data.DataColumn("INDAMOUNT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINDAMOUNT);
                this.columnINITMARGIN = new global::System.Data.DataColumn("INITMARGIN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINITMARGIN);
                this.columnCTPY_THRESHOLD = new global::System.Data.DataColumn("CTPY_THRESHOLD", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCTPY_THRESHOLD);
                this.columnKK_THRESHOLD = new global::System.Data.DataColumn("KK_THRESHOLD", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKK_THRESHOLD);
                this.columnMIN_TRANSFER = new global::System.Data.DataColumn("MIN_TRANSFER", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMIN_TRANSFER);
                this.columnROUNDING_AMT = new global::System.Data.DataColumn("ROUNDING_AMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROUNDING_AMT);
                this.columnCCY = new global::System.Data.DataColumn("CCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCY);
                this.columnSETTLED_AMT = new global::System.Data.DataColumn("SETTLED_AMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSETTLED_AMT);
                this.columnPENDING_AMT = new global::System.Data.DataColumn("PENDING_AMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENDING_AMT);
                this.columnEXPOSURE = new global::System.Data.DataColumn("EXPOSURE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEXPOSURE);
                this.columnLOCAL_CCY_EXP = new global::System.Data.DataColumn("LOCAL_CCY_EXP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOCAL_CCY_EXP);
                this.columnREPORT_DATE = new global::System.Data.DataColumn("REPORT_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREPORT_DATE);
                this.columnEXP_RETURN = new global::System.Data.DataColumn("EXP_RETURN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEXP_RETURN);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSRow NewTB_TR101OBOCOLSRow() {
                return ((TB_TR101OBOCOLSRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TB_TR101OBOCOLSRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TB_TR101OBOCOLSRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TB_TR101OBOCOLSRowChanged != null)) {
                    this.TB_TR101OBOCOLSRowChanged(this, new TB_TR101OBOCOLSRowChangeEvent(((TB_TR101OBOCOLSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TB_TR101OBOCOLSRowChanging != null)) {
                    this.TB_TR101OBOCOLSRowChanging(this, new TB_TR101OBOCOLSRowChangeEvent(((TB_TR101OBOCOLSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TB_TR101OBOCOLSRowDeleted != null)) {
                    this.TB_TR101OBOCOLSRowDeleted(this, new TB_TR101OBOCOLSRowChangeEvent(((TB_TR101OBOCOLSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TB_TR101OBOCOLSRowDeleting != null)) {
                    this.TB_TR101OBOCOLSRowDeleting(this, new TB_TR101OBOCOLSRowChangeEvent(((TB_TR101OBOCOLSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTB_TR101OBOCOLSRow(TB_TR101OBOCOLSRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_TR101OBOCOLS ds = new DS_TR101OBOCOLS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TB_TR101OBOCOLSDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TB_TR101OBOCOLSRow : global::System.Data.DataRow {
            
            private TB_TR101OBOCOLSDataTable tableTB_TR101OBOCOLS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR101OBOCOLSRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTB_TR101OBOCOLS = ((TB_TR101OBOCOLSDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CUST {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR101OBOCOLS.CUSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CUST\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.CUSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal INDAMOUNT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.INDAMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INDAMOUNT\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.INDAMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal INITMARGIN {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.INITMARGINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INITMARGIN\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.INITMARGINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal CTPY_THRESHOLD {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.CTPY_THRESHOLDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CTPY_THRESHOLD\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.CTPY_THRESHOLDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal KK_THRESHOLD {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.KK_THRESHOLDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KK_THRESHOLD\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.KK_THRESHOLDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal MIN_TRANSFER {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.MIN_TRANSFERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MIN_TRANSFER\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.MIN_TRANSFERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal ROUNDING_AMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.ROUNDING_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROUNDING_AMT\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.ROUNDING_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CCY {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR101OBOCOLS.CCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCY\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.CCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SETTLED_AMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.SETTLED_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SETTLED_AMT\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.SETTLED_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal PENDING_AMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.PENDING_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENDING_AMT\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.PENDING_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal EXPOSURE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR101OBOCOLS.EXPOSUREColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EXPOSURE\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.EXPOSUREColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LOCAL_CCY_EXP {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR101OBOCOLS.LOCAL_CCY_EXPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LOCAL_CCY_EXP\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.LOCAL_CCY_EXPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string REPORT_DATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR101OBOCOLS.REPORT_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REPORT_DATE\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.REPORT_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EXP_RETURN {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR101OBOCOLS.EXP_RETURNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EXP_RETURN\' in table \'TB_TR101OBOCOLS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR101OBOCOLS.EXP_RETURNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCUSTNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.CUSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCUSTNull() {
                this[this.tableTB_TR101OBOCOLS.CUSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINDAMOUNTNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.INDAMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINDAMOUNTNull() {
                this[this.tableTB_TR101OBOCOLS.INDAMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINITMARGINNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.INITMARGINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINITMARGINNull() {
                this[this.tableTB_TR101OBOCOLS.INITMARGINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCTPY_THRESHOLDNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.CTPY_THRESHOLDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCTPY_THRESHOLDNull() {
                this[this.tableTB_TR101OBOCOLS.CTPY_THRESHOLDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKK_THRESHOLDNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.KK_THRESHOLDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKK_THRESHOLDNull() {
                this[this.tableTB_TR101OBOCOLS.KK_THRESHOLDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMIN_TRANSFERNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.MIN_TRANSFERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMIN_TRANSFERNull() {
                this[this.tableTB_TR101OBOCOLS.MIN_TRANSFERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsROUNDING_AMTNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.ROUNDING_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetROUNDING_AMTNull() {
                this[this.tableTB_TR101OBOCOLS.ROUNDING_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.CCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYNull() {
                this[this.tableTB_TR101OBOCOLS.CCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSETTLED_AMTNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.SETTLED_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSETTLED_AMTNull() {
                this[this.tableTB_TR101OBOCOLS.SETTLED_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENDING_AMTNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.PENDING_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENDING_AMTNull() {
                this[this.tableTB_TR101OBOCOLS.PENDING_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEXPOSURENull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.EXPOSUREColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEXPOSURENull() {
                this[this.tableTB_TR101OBOCOLS.EXPOSUREColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLOCAL_CCY_EXPNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.LOCAL_CCY_EXPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLOCAL_CCY_EXPNull() {
                this[this.tableTB_TR101OBOCOLS.LOCAL_CCY_EXPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsREPORT_DATENull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.REPORT_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetREPORT_DATENull() {
                this[this.tableTB_TR101OBOCOLS.REPORT_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEXP_RETURNNull() {
                return this.IsNull(this.tableTB_TR101OBOCOLS.EXP_RETURNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEXP_RETURNNull() {
                this[this.tableTB_TR101OBOCOLS.EXP_RETURNColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TB_TR101OBOCOLSRowChangeEvent : global::System.EventArgs {
            
            private TB_TR101OBOCOLSRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSRowChangeEvent(TB_TR101OBOCOLSRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR101OBOCOLSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591