//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace KKB.Treasury.TreasuryReport.DSD_Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_TR145NOSTROAVG")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_TR145NOSTROAVG : global::System.Data.DataSet {
        
        private TB_TR145NOSTROAVGDataTable tableTB_TR145NOSTROAVG;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_TR145NOSTROAVG() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_TR145NOSTROAVG(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TB_TR145NOSTROAVG"] != null)) {
                    base.Tables.Add(new TB_TR145NOSTROAVGDataTable(ds.Tables["TB_TR145NOSTROAVG"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TB_TR145NOSTROAVGDataTable TB_TR145NOSTROAVG {
            get {
                return this.tableTB_TR145NOSTROAVG;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DS_TR145NOSTROAVG cln = ((DS_TR145NOSTROAVG)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TB_TR145NOSTROAVG"] != null)) {
                    base.Tables.Add(new TB_TR145NOSTROAVGDataTable(ds.Tables["TB_TR145NOSTROAVG"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTB_TR145NOSTROAVG = ((TB_TR145NOSTROAVGDataTable)(base.Tables["TB_TR145NOSTROAVG"]));
            if ((initTable == true)) {
                if ((this.tableTB_TR145NOSTROAVG != null)) {
                    this.tableTB_TR145NOSTROAVG.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_TR145NOSTROAVG";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_TR145NOSTROAVG.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTB_TR145NOSTROAVG = new TB_TR145NOSTROAVGDataTable();
            base.Tables.Add(this.tableTB_TR145NOSTROAVG);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTB_TR145NOSTROAVG() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_TR145NOSTROAVG ds = new DS_TR145NOSTROAVG();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TB_TR145NOSTROAVGRowChangeEventHandler(object sender, TB_TR145NOSTROAVGRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TB_TR145NOSTROAVGDataTable : global::System.Data.TypedTableBase<TB_TR145NOSTROAVGRow> {
            
            private global::System.Data.DataColumn columnSTARTDATE;
            
            private global::System.Data.DataColumn columnENDDATE;
            
            private global::System.Data.DataColumn columnCCY;
            
            private global::System.Data.DataColumn columnDESCRIPTION;
            
            private global::System.Data.DataColumn columnVDATE;
            
            private global::System.Data.DataColumn columnBUYAMT;
            
            private global::System.Data.DataColumn columnSELLAMT;
            
            private global::System.Data.DataColumn columnSTATEDATE;
            
            private global::System.Data.DataColumn columnSTATERATE;
            
            private global::System.Data.DataColumn columnOPICSDATE;
            
            private global::System.Data.DataColumn columnOPICSRATE;
            
            private global::System.Data.DataColumn columnSTATEMOVE;
            
            private global::System.Data.DataColumn columnOPICSMOVE;
            
            private global::System.Data.DataColumn columnADJDIFSPOTRATE;
            
            private global::System.Data.DataColumn columnADJPLTHB;
            
            private global::System.Data.DataColumn columnBALANCECCY;
            
            private global::System.Data.DataColumn columnBALANCETHB;
            
            private global::System.Data.DataColumn columnEXCHRATEAVG;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGDataTable() {
                this.TableName = "TB_TR145NOSTROAVG";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR145NOSTROAVGDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TB_TR145NOSTROAVGDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STARTDATEColumn {
                get {
                    return this.columnSTARTDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ENDDATEColumn {
                get {
                    return this.columnENDDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYColumn {
                get {
                    return this.columnCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DESCRIPTIONColumn {
                get {
                    return this.columnDESCRIPTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn VDATEColumn {
                get {
                    return this.columnVDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BUYAMTColumn {
                get {
                    return this.columnBUYAMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SELLAMTColumn {
                get {
                    return this.columnSELLAMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STATEDATEColumn {
                get {
                    return this.columnSTATEDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STATERATEColumn {
                get {
                    return this.columnSTATERATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPICSDATEColumn {
                get {
                    return this.columnOPICSDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPICSRATEColumn {
                get {
                    return this.columnOPICSRATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STATEMOVEColumn {
                get {
                    return this.columnSTATEMOVE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPICSMOVEColumn {
                get {
                    return this.columnOPICSMOVE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ADJDIFSPOTRATEColumn {
                get {
                    return this.columnADJDIFSPOTRATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ADJPLTHBColumn {
                get {
                    return this.columnADJPLTHB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BALANCECCYColumn {
                get {
                    return this.columnBALANCECCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BALANCETHBColumn {
                get {
                    return this.columnBALANCETHB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EXCHRATEAVGColumn {
                get {
                    return this.columnEXCHRATEAVG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGRow this[int index] {
                get {
                    return ((TB_TR145NOSTROAVGRow)(this.Rows[index]));
                }
            }
            
            public event TB_TR145NOSTROAVGRowChangeEventHandler TB_TR145NOSTROAVGRowChanging;
            
            public event TB_TR145NOSTROAVGRowChangeEventHandler TB_TR145NOSTROAVGRowChanged;
            
            public event TB_TR145NOSTROAVGRowChangeEventHandler TB_TR145NOSTROAVGRowDeleting;
            
            public event TB_TR145NOSTROAVGRowChangeEventHandler TB_TR145NOSTROAVGRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTB_TR145NOSTROAVGRow(TB_TR145NOSTROAVGRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGRow AddTB_TR145NOSTROAVGRow(
                        string STARTDATE, 
                        string ENDDATE, 
                        string CCY, 
                        string DESCRIPTION, 
                        string VDATE, 
                        decimal BUYAMT, 
                        decimal SELLAMT, 
                        string STATEDATE, 
                        decimal STATERATE, 
                        string OPICSDATE, 
                        decimal OPICSRATE, 
                        decimal STATEMOVE, 
                        decimal OPICSMOVE, 
                        decimal ADJDIFSPOTRATE, 
                        decimal ADJPLTHB, 
                        decimal BALANCECCY, 
                        decimal BALANCETHB, 
                        decimal EXCHRATEAVG) {
                TB_TR145NOSTROAVGRow rowTB_TR145NOSTROAVGRow = ((TB_TR145NOSTROAVGRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        STARTDATE,
                        ENDDATE,
                        CCY,
                        DESCRIPTION,
                        VDATE,
                        BUYAMT,
                        SELLAMT,
                        STATEDATE,
                        STATERATE,
                        OPICSDATE,
                        OPICSRATE,
                        STATEMOVE,
                        OPICSMOVE,
                        ADJDIFSPOTRATE,
                        ADJPLTHB,
                        BALANCECCY,
                        BALANCETHB,
                        EXCHRATEAVG};
                rowTB_TR145NOSTROAVGRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTB_TR145NOSTROAVGRow);
                return rowTB_TR145NOSTROAVGRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TB_TR145NOSTROAVGDataTable cln = ((TB_TR145NOSTROAVGDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TB_TR145NOSTROAVGDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSTARTDATE = base.Columns["STARTDATE"];
                this.columnENDDATE = base.Columns["ENDDATE"];
                this.columnCCY = base.Columns["CCY"];
                this.columnDESCRIPTION = base.Columns["DESCRIPTION"];
                this.columnVDATE = base.Columns["VDATE"];
                this.columnBUYAMT = base.Columns["BUYAMT"];
                this.columnSELLAMT = base.Columns["SELLAMT"];
                this.columnSTATEDATE = base.Columns["STATEDATE"];
                this.columnSTATERATE = base.Columns["STATERATE"];
                this.columnOPICSDATE = base.Columns["OPICSDATE"];
                this.columnOPICSRATE = base.Columns["OPICSRATE"];
                this.columnSTATEMOVE = base.Columns["STATEMOVE"];
                this.columnOPICSMOVE = base.Columns["OPICSMOVE"];
                this.columnADJDIFSPOTRATE = base.Columns["ADJDIFSPOTRATE"];
                this.columnADJPLTHB = base.Columns["ADJPLTHB"];
                this.columnBALANCECCY = base.Columns["BALANCECCY"];
                this.columnBALANCETHB = base.Columns["BALANCETHB"];
                this.columnEXCHRATEAVG = base.Columns["EXCHRATEAVG"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSTARTDATE = new global::System.Data.DataColumn("STARTDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTARTDATE);
                this.columnENDDATE = new global::System.Data.DataColumn("ENDDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnENDDATE);
                this.columnCCY = new global::System.Data.DataColumn("CCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCY);
                this.columnDESCRIPTION = new global::System.Data.DataColumn("DESCRIPTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESCRIPTION);
                this.columnVDATE = new global::System.Data.DataColumn("VDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVDATE);
                this.columnBUYAMT = new global::System.Data.DataColumn("BUYAMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYAMT);
                this.columnSELLAMT = new global::System.Data.DataColumn("SELLAMT", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSELLAMT);
                this.columnSTATEDATE = new global::System.Data.DataColumn("STATEDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATEDATE);
                this.columnSTATERATE = new global::System.Data.DataColumn("STATERATE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATERATE);
                this.columnOPICSDATE = new global::System.Data.DataColumn("OPICSDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPICSDATE);
                this.columnOPICSRATE = new global::System.Data.DataColumn("OPICSRATE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPICSRATE);
                this.columnSTATEMOVE = new global::System.Data.DataColumn("STATEMOVE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATEMOVE);
                this.columnOPICSMOVE = new global::System.Data.DataColumn("OPICSMOVE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPICSMOVE);
                this.columnADJDIFSPOTRATE = new global::System.Data.DataColumn("ADJDIFSPOTRATE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADJDIFSPOTRATE);
                this.columnADJPLTHB = new global::System.Data.DataColumn("ADJPLTHB", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADJPLTHB);
                this.columnBALANCECCY = new global::System.Data.DataColumn("BALANCECCY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCECCY);
                this.columnBALANCETHB = new global::System.Data.DataColumn("BALANCETHB", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCETHB);
                this.columnEXCHRATEAVG = new global::System.Data.DataColumn("EXCHRATEAVG", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEXCHRATEAVG);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGRow NewTB_TR145NOSTROAVGRow() {
                return ((TB_TR145NOSTROAVGRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TB_TR145NOSTROAVGRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TB_TR145NOSTROAVGRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TB_TR145NOSTROAVGRowChanged != null)) {
                    this.TB_TR145NOSTROAVGRowChanged(this, new TB_TR145NOSTROAVGRowChangeEvent(((TB_TR145NOSTROAVGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TB_TR145NOSTROAVGRowChanging != null)) {
                    this.TB_TR145NOSTROAVGRowChanging(this, new TB_TR145NOSTROAVGRowChangeEvent(((TB_TR145NOSTROAVGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TB_TR145NOSTROAVGRowDeleted != null)) {
                    this.TB_TR145NOSTROAVGRowDeleted(this, new TB_TR145NOSTROAVGRowChangeEvent(((TB_TR145NOSTROAVGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TB_TR145NOSTROAVGRowDeleting != null)) {
                    this.TB_TR145NOSTROAVGRowDeleting(this, new TB_TR145NOSTROAVGRowChangeEvent(((TB_TR145NOSTROAVGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTB_TR145NOSTROAVGRow(TB_TR145NOSTROAVGRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_TR145NOSTROAVG ds = new DS_TR145NOSTROAVG();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TB_TR145NOSTROAVGDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TB_TR145NOSTROAVGRow : global::System.Data.DataRow {
            
            private TB_TR145NOSTROAVGDataTable tableTB_TR145NOSTROAVG;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TB_TR145NOSTROAVGRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTB_TR145NOSTROAVG = ((TB_TR145NOSTROAVGDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STARTDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.STARTDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STARTDATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.STARTDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ENDDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.ENDDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ENDDATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.ENDDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CCY {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.CCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCY\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.CCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DESCRIPTION {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.DESCRIPTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DESCRIPTION\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.DESCRIPTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string VDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.VDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'VDATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.VDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal BUYAMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.BUYAMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BUYAMT\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.BUYAMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SELLAMT {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.SELLAMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SELLAMT\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.SELLAMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STATEDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.STATEDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STATEDATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.STATEDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal STATERATE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.STATERATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STATERATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.STATERATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OPICSDATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_TR145NOSTROAVG.OPICSDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPICSDATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.OPICSDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal OPICSRATE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.OPICSRATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPICSRATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.OPICSRATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal STATEMOVE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.STATEMOVEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STATEMOVE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.STATEMOVEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal OPICSMOVE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.OPICSMOVEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPICSMOVE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.OPICSMOVEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal ADJDIFSPOTRATE {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.ADJDIFSPOTRATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADJDIFSPOTRATE\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.ADJDIFSPOTRATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal ADJPLTHB {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.ADJPLTHBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADJPLTHB\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.ADJPLTHBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal BALANCECCY {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.BALANCECCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCECCY\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.BALANCECCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal BALANCETHB {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.BALANCETHBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCETHB\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.BALANCETHBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal EXCHRATEAVG {
                get {
                    try {
                        return ((decimal)(this[this.tableTB_TR145NOSTROAVG.EXCHRATEAVGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EXCHRATEAVG\' in table \'TB_TR145NOSTROAVG\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_TR145NOSTROAVG.EXCHRATEAVGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTARTDATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.STARTDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTARTDATENull() {
                this[this.tableTB_TR145NOSTROAVG.STARTDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsENDDATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.ENDDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetENDDATENull() {
                this[this.tableTB_TR145NOSTROAVG.ENDDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.CCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYNull() {
                this[this.tableTB_TR145NOSTROAVG.CCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDESCRIPTIONNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.DESCRIPTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDESCRIPTIONNull() {
                this[this.tableTB_TR145NOSTROAVG.DESCRIPTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsVDATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.VDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetVDATENull() {
                this[this.tableTB_TR145NOSTROAVG.VDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBUYAMTNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.BUYAMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBUYAMTNull() {
                this[this.tableTB_TR145NOSTROAVG.BUYAMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSELLAMTNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.SELLAMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSELLAMTNull() {
                this[this.tableTB_TR145NOSTROAVG.SELLAMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTATEDATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.STATEDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTATEDATENull() {
                this[this.tableTB_TR145NOSTROAVG.STATEDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTATERATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.STATERATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTATERATENull() {
                this[this.tableTB_TR145NOSTROAVG.STATERATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPICSDATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.OPICSDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPICSDATENull() {
                this[this.tableTB_TR145NOSTROAVG.OPICSDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPICSRATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.OPICSRATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPICSRATENull() {
                this[this.tableTB_TR145NOSTROAVG.OPICSRATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTATEMOVENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.STATEMOVEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTATEMOVENull() {
                this[this.tableTB_TR145NOSTROAVG.STATEMOVEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPICSMOVENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.OPICSMOVEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPICSMOVENull() {
                this[this.tableTB_TR145NOSTROAVG.OPICSMOVEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsADJDIFSPOTRATENull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.ADJDIFSPOTRATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetADJDIFSPOTRATENull() {
                this[this.tableTB_TR145NOSTROAVG.ADJDIFSPOTRATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsADJPLTHBNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.ADJPLTHBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetADJPLTHBNull() {
                this[this.tableTB_TR145NOSTROAVG.ADJPLTHBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBALANCECCYNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.BALANCECCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBALANCECCYNull() {
                this[this.tableTB_TR145NOSTROAVG.BALANCECCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBALANCETHBNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.BALANCETHBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBALANCETHBNull() {
                this[this.tableTB_TR145NOSTROAVG.BALANCETHBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEXCHRATEAVGNull() {
                return this.IsNull(this.tableTB_TR145NOSTROAVG.EXCHRATEAVGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEXCHRATEAVGNull() {
                this[this.tableTB_TR145NOSTROAVG.EXCHRATEAVGColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TB_TR145NOSTROAVGRowChangeEvent : global::System.EventArgs {
            
            private TB_TR145NOSTROAVGRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGRowChangeEvent(TB_TR145NOSTROAVGRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TB_TR145NOSTROAVGRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591